# This file is generated by cargo_embargo.
# Do not modify this file after the LOCAL_DIR line
# because the changes will be overridden on upgrade.
# Content before the first line starting with LOCAL_DIR is preserved.

LOCAL_DIR := $(GET_LOCAL_DIR)
MODULE := $(LOCAL_DIR)
MODULE_CRATE_NAME := openssl
MODULE_RUST_CRATE_TYPES := rlib
MODULE_SRCS := $(LOCAL_DIR)/src/lib.rs
MODULE_RUST_EDITION := 2018
MODULE_RUSTFLAGS += \
	--cfg 'feature="unstable_boringssl"' \
	--cfg 'boringssl'

MODULE_LIBRARY_DEPS := \
	$(call FIND_CRATE,bitflags) \
	$(call FIND_CRATE,cfg-if) \
	$(call FIND_CRATE,foreign-types) \
	$(call FIND_CRATE,libc) \
	$(call FIND_CRATE,once_cell) \
	$(call FIND_CRATE,openssl-macros) \
	$(call FIND_CRATE,openssl-sys)

include make/library.mk
