[package]
name = "openssl"
version = "0.10.38"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "Apache-2.0"
description = "OpenSSL bindings"
repository = "https://github.com/sfackler/rust-openssl"
readme = "README.md"
keywords = ["crypto", "tls", "ssl", "dtls"]
categories = ["cryptography", "api-bindings"]
edition = "2018"

# these are deprecated and don't do anything anymore
[features]
v101 = []
v102 = []
v110 = []
v111 = []

vendored = ['ffi/vendored']
bindgen = ['ffi/bindgen']
boringssl = ["bssl-ffi"]
default = ["ffi"]

[dependencies]
bitflags = "1.0"
cfg-if = "1.0"
foreign-types = "0.3.1"
libc = "0.2"
once_cell = "1.5.2"

openssl-macros = { path = "../openssl-macros" }
bssl-ffi = { package = "bssl-sys", version = "0.1.0", path = "../../boringssl/build/rust", optional=true }
ffi = { package = "openssl-sys", version = "0.9.69", path = "../openssl-sys", optional = true}

[dev-dependencies]
hex = "0.3"
